server:
  port: 8080
  servlet:
    context-path: /spaceship

spring:
  application:
    name: space-ships
    profiles:
    #    active: init-test-data
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCH ER
    jackson:
      serialization:
        write-dates-as-timestamps: false
    #    default-property-inclusion: non_null
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 78h4317h
    hikari:
      schema: spaceship
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "spaceship";
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: spaceship
    liquibase-schema: spaceship